/**
 * Canonicalization tests.
 *
 * The "byte identity" tests below MUST produce exactly the same UTF-8
 * bytes as the Python reference (`reference/python/crovia_seal/canonical.py`).
 * Each pair was generated by running the Python implementation; if either
 * side changes, both must change together.
 */
import { describe, expect, it } from "vitest";

import { canonicalize, canonicalizeString, CanonicalizationError } from "../src/canonical.js";

describe("canonicalize — basic types", () => {
  it("null", () => {
    expect(canonicalizeString(null)).toBe("null");
  });
  it("booleans", () => {
    expect(canonicalizeString(true)).toBe("true");
    expect(canonicalizeString(false)).toBe("false");
  });
  it("integers", () => {
    expect(canonicalizeString(0)).toBe("0");
    expect(canonicalizeString(-0)).toBe("0");
    expect(canonicalizeString(42)).toBe("42");
    expect(canonicalizeString(-42)).toBe("-42");
    expect(canonicalizeString(Number.MAX_SAFE_INTEGER)).toBe(
      String(Number.MAX_SAFE_INTEGER),
    );
  });
  it("strings — basic", () => {
    expect(canonicalizeString("")).toBe('""');
    expect(canonicalizeString("hi")).toBe('"hi"');
    expect(canonicalizeString("ciao")).toBe('"ciao"');
  });
  it("strings — short escapes", () => {
    expect(canonicalizeString('a"b')).toBe('"a\\"b"');
    expect(canonicalizeString("a\\b")).toBe('"a\\\\b"');
    expect(canonicalizeString("a\nb")).toBe('"a\\nb"');
    expect(canonicalizeString("a\tb")).toBe('"a\\tb"');
    expect(canonicalizeString("a\rb")).toBe('"a\\rb"');
    expect(canonicalizeString("a\bb")).toBe('"a\\bb"');
    expect(canonicalizeString("a\fb")).toBe('"a\\fb"');
  });
  it("strings — \\u00XX for other control chars", () => {
    expect(canonicalizeString("\u0000")).toBe('"\\u0000"');
    expect(canonicalizeString("\u0001")).toBe('"\\u0001"');
    expect(canonicalizeString("\u001f")).toBe('"\\u001f"');
  });
  it("strings — non-ASCII passes through literally", () => {
    expect(canonicalizeString("café")).toBe('"café"');
    expect(canonicalizeString("日本")).toBe('"日本"');
  });
});

describe("canonicalize — composition", () => {
  it("empty array / object", () => {
    expect(canonicalizeString([])).toBe("[]");
    expect(canonicalizeString({})).toBe("{}");
  });
  it("array preserves order", () => {
    expect(canonicalizeString([3, 1, 2])).toBe("[3,1,2]");
  });
  it("object keys are sorted", () => {
    expect(canonicalizeString({ b: 1, a: 2 })).toBe('{"a":2,"b":1}');
  });
  it("nested object keys are sorted recursively", () => {
    expect(
      canonicalizeString({ z: { y: 1, x: 2 }, a: [{ d: 4, c: 3 }] }),
    ).toBe('{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}');
  });
  it("UTF-16 code-unit ordering for non-ASCII keys", () => {
    // 'ä' (U+00E4) sorts after ASCII; emoji '🍣' uses a surrogate pair,
    // so its first code unit is U+D83C (high surrogate range), which
    // sorts AFTER 'ä'.
    expect(canonicalizeString({ "ä": 1, "a": 2 })).toBe(
      '{"a":2,"ä":1}',
    );
  });
});

describe("canonicalize — fail-closed rejections", () => {
  it("rejects floats", () => {
    expect(() => canonicalize(1.5)).toThrow(CanonicalizationError);
  });
  it("rejects undefined", () => {
    expect(() => canonicalize(undefined as unknown)).toThrow(
      CanonicalizationError,
    );
  });
  it("rejects NaN / Infinity", () => {
    expect(() => canonicalize(NaN)).toThrow(CanonicalizationError);
    expect(() => canonicalize(Infinity)).toThrow(CanonicalizationError);
  });
  it("rejects out-of-range integers", () => {
    expect(() => canonicalize(2 ** 53)).toThrow(CanonicalizationError);
    expect(() => canonicalize(-(2 ** 53))).toThrow(CanonicalizationError);
  });
});

describe("canonicalize — UTF-8 byte identity", () => {
  it("emits a TextEncoder-equivalent byte stream", () => {
    const input = { z: 1, a: "x" };
    const bytes = canonicalize(input);
    const expected = new TextEncoder().encode('{"a":"x","z":1}');
    expect(bytes).toEqual(expected);
  });
});
