/**
 * Cross-SDK interop — Python sealed it, JS must verify.
 *
 * The fixture below was generated by the Python SDK
 * (`sdk/python/`) using:
 *
 *   from crovia_seal import seal, generate_key
 *   key = generate_key()
 *   r = seal({"interop":"py->js","n":42}, key=key,
 *            payload_type="interop/test",
 *            issued_at="2026-05-07T17:10:00.000Z")
 *
 * If this test fails, byte-identity between Python and JS is broken
 * — that is a P0 conformance bug.
 */
import { describe, expect, it } from "vitest";

import { verify } from "../src/index.js";

const PY_RECEIPT = {
  v: "crovia.receipt.v1",
  id: "cr_2026_ZXWMVM5UTZZQMEO36FDJXFHPWI",
  issued_at: "2026-05-07T17:10:00.000Z",
  payload_hash:
    "sha256:94b9f44ff7d3b3a0a9d1105bfdc4302068dd10f01efebbabdc6328544f9a01a7",
  payload_alg: "sha256",
  payload_type: "interop/test",
  prev: null,
  seq: 0,
  signer:
    "f4cb002d45b82aa3f516f4b504ad34ee07bdc629e51b48a84dcd0f80e2098531",
  sig_alg: "ed25519",
  canon: "csc-1",
  domain: "CROVIA-RECEIPT-v1",
  sig:
    "84309f29ce9a86a40c7cfd1f3a8f8f3e57f4367fcff8252ffe266f8004c64537fbf75a5042ff30754919a56d1205535248d3e1fbaaaf2550e44e147b91231d01",
} as const;

const PY_PAYLOAD = { interop: "py->js", n: 42 };

describe("cross-SDK interop: Python → JS", () => {
  it("verifies a receipt produced by the Python SDK (signature + structure)", async () => {
    const result = await verify(PY_RECEIPT);
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
    expect(result.id).toBe(PY_RECEIPT.id);
    expect(result.signer).toBe(PY_RECEIPT.signer);
  });

  it("verifies a Python-sealed receipt against its original payload", async () => {
    const result = await verify(PY_RECEIPT, PY_PAYLOAD);
    expect(result.valid).toBe(true);
  });

  it("rejects a Python-sealed receipt with mismatched payload", async () => {
    const result = await verify(PY_RECEIPT, { interop: "py->js", n: 43 });
    expect(result.valid).toBe(false);
  });
});
