/**
 * Cross-language byte-identity tests.
 *
 * For each fixture, we verify that the JS canonicalization produces
 * exactly the bytes that the Python CSC-1 reference implementation
 * produces. The expected bytes are generated by running the Python
 * reference (see scripts/gen_fixtures.py).
 *
 * If either implementation changes, regenerate the fixtures and update
 * this file. The conformance contract requires both impls to remain
 * byte-identical forever.
 */
import { describe, expect, it } from "vitest";

import { canonicalize, canonicalizeString } from "../src/canonical.js";

interface Fixture {
  name: string;
  value: unknown;
  expected: string;
}

// Hand-curated fixtures — these test specific CSC-1 invariants and were
// validated by running Python's `crovia_seal.canonical.canonicalize()`
// on the exact same value.
const FIXTURES: Fixture[] = [
  { name: "null", value: null, expected: "null" },
  { name: "true", value: true, expected: "true" },
  { name: "false", value: false, expected: "false" },
  { name: "zero", value: 0, expected: "0" },
  { name: "positive int", value: 42, expected: "42" },
  { name: "negative int", value: -1, expected: "-1" },
  { name: "max safe int", value: 2 ** 53 - 1, expected: "9007199254740991" },
  { name: "empty string", value: "", expected: '""' },
  { name: "ascii string", value: "hi", expected: '"hi"' },
  { name: "newline escape", value: "a\nb", expected: '"a\\nb"' },
  { name: "tab escape", value: "a\tb", expected: '"a\\tb"' },
  { name: "quote escape", value: 'a"b', expected: '"a\\"b"' },
  { name: "backslash escape", value: "a\\b", expected: '"a\\\\b"' },
  { name: "control char \\u0001", value: "\u0001", expected: '"\\u0001"' },
  { name: "non-ASCII passes through", value: "café", expected: '"café"' },
  { name: "Japanese", value: "日本", expected: '"日本"' },
  { name: "empty array", value: [], expected: "[]" },
  { name: "array preserves order", value: [3, 1, 2], expected: "[3,1,2]" },
  { name: "empty object", value: {}, expected: "{}" },
  { name: "object keys sorted", value: { b: 1, a: 2 }, expected: '{"a":2,"b":1}' },
  {
    name: "nested keys sorted recursively",
    value: { z: { y: 1, x: 2 }, a: [{ d: 4, c: 3 }] },
    expected: '{"a":[{"c":3,"d":4}],"z":{"x":2,"y":1}}',
  },
  {
    name: "ASCII before non-ASCII",
    value: { "ä": 1, a: 2 },
    expected: '{"a":2,"ä":1}',
  },
  {
    name: "realistic AI output payload",
    value: {
      model: "gpt-4o",
      output: "Hello, world.",
      params: { temperature: "0.7", top_p: "1.0" },
    },
    expected:
      '{"model":"gpt-4o","output":"Hello, world.","params":{"temperature":"0.7","top_p":"1.0"}}',
  },
];

describe("CSC-1 byte identity (vs Python reference)", () => {
  for (const fx of FIXTURES) {
    it(fx.name, () => {
      expect(canonicalizeString(fx.value)).toBe(fx.expected);
      // UTF-8 byte length must match too.
      const bytes = canonicalize(fx.value);
      const expectedBytes = new TextEncoder().encode(fx.expected);
      expect(bytes.length).toBe(expectedBytes.length);
      expect(bytes).toEqual(expectedBytes);
    });
  }
});
